#!/usr/bin/env python3
"""Generate the self-contained browser fixture and Python-oracle bundle."""

from __future__ import annotations

import base64
import json
import os
import pathlib

import python_oracle


PACKAGE_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_PICOTOOL_ROOT = (PACKAGE_ROOT / "vendor" / "picotool"
                         if (PACKAGE_ROOT / "vendor" / "picotool").exists()
                         else PACKAGE_ROOT.parents[1] / "vendor" / "picotool")
PICOTOOL_ROOT = pathlib.Path(os.environ.get("PICOTOOL_ROOT", DEFAULT_PICOTOOL_ROOT))
TESTDATA = PICOTOOL_ROOT / "tests" / "testdata"
OUTPUT = pathlib.Path(__file__).resolve().parents[1] / "browser" / "fixture-data.js"


def fixture_paths() -> list[pathlib.Path]:
    return sorted((*TESTDATA.glob("*.p8"), *TESTDATA.glob("*.p8.png")), key=lambda path: path.name)


def main() -> None:
    fixtures = []
    oracle_cases = python_oracle.conformance_cases()
    for path in fixture_paths():
        source = path.read_bytes()
        is_png = path.name.lower().endswith(".p8.png")
        formatter = python_oracle.png_formatter_result if is_png else python_oracle.formatter_result
        fixtures.append({
            "name": path.name,
            "type": "image/png" if is_png else "text/plain",
            "base64": base64.b64encode(source).decode("ascii"),
        })
        oracle_cases.append({"id": f"fixture/{path.name}", **formatter(source, path.name)})

    bundle = {
        "fixtures": fixtures,
        "oracle": {
            "schema": python_oracle.SCHEMA,
            "implementation": "python-picotool-bundled",
            "parity": {"cases": oracle_cases},
        },
    }
    payload = json.dumps(bundle, separators=(",", ":"), sort_keys=True)
    OUTPUT.write_text(
        "// Generated by tools/generate_browser_fixtures.py; do not edit.\n"
        f"globalThis.PicotoolBundledFixtures = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(fixtures)} fixtures to {OUTPUT.relative_to(PACKAGE_ROOT)}")


if __name__ == "__main__":
    main()
